config/routes.rb
Rails.application.routes.draw do
  root 'global_pages#home'
  get '/home', to: 'global_pages#home'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/edit/password', to: 'password#edit'

  get '/signup', to: 'global_pages#signup'
  get '/signupcandidato', to:'candidatos#new'
  get '/signupentidade', to:'entidades#new'
  get '/new/offer', to:'offers#new'
  get 'new/news', to:'news#new'

  get '/candidatos', to:'candidatos#index'
  get '/entidades', to: 'entidades#index'
  get '/offers', to: 'offers#index'
  get '/news', to: 'news#index'
  
  resources :candidatos do
    member do
      get :offerings, :offerends
    end
  end

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :users, :entidades, :offers, :news
  resources :candidaturas, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

  #BACKOFFICE
  get '/backoffice', to: 'backoffice#home'
  get '/backoffice/users', to: 'backoffice#index_users'
  get '/backoffice/news', to: 'backoffice#index_news'
  get '/backoffice/users/:id', to: 'backoffice#show_users', as: 'backoffice_show_users'
  get '/backoffice/news/:id', to: 'backoffice#show_news', as: 'backoffice_show_news'
  get '/backoffice/news/:id/edit', to:'backoffice#edit_news', as: 'backoffice_edit_news'
  patch '/backoffice/news/:id/edit', to:'news#update'
  get '/backoffice/users/:id/edit', to:'backoffice#edit_users', as: 'backoffice_edit_users'
  get '/backoffice/users/:id/edit_password', to:'backoffice#edit_user_password', as: 'backoffice_edit_user_password'
  patch '/backoffice/users/:id/edit_password', to:'users#update'
  patch '/backoffice/users/:id/edit', to:'users#update'
  post '/backoffice/new', to:'users#create'
  resources :backoffice
  
end

app/controllers/backoffice_controller.rb
class BackofficeController < ApplicationController
    before_action :logged_in_user
  
    def home
        if current_user.admin?
            render 'backoffice/home'
        end
    end
  
    def new
      @user = User.new
    end
  
    def index_news
      @news = News.all.order(updated_at: :desc)
      @news  = @news.title(params[:title]) if params[:title].present?
      @news = @news.paginate(page: params[:page], per_page: 10)
    end
  
    def index_users
      @users = User.all.order(updated_at: :desc)
      @users = @users.type(params[:type]) if params[:type].present?
      @users = @users.search(params[:search]) if params[:search].present?
      @users = @users.paginate(page: params[:page], per_page: 10)
    end
  
    def show_users
      @user = User.find(params[:id])
    end
  
    def show_news
      @news = News.find(params[:id])
    end
  
    def edit_users
      @user = User.find(params[:id])
    end
  
    def edit_user_password
      @user = User.find(params[:id])
    end
  
    def edit_news
      @news = News.find(params[:id])
    end
  
  end

app/helpers/backoffice_helper.rb
module BackofficeHelper
end

app/views/backoffice/_edit.html.erb
<% provide(:title, @news.title) %>
<h3><%= @news.title %></h3>

<div class="row">
    <div class="col-md-12">
        <%= form_with(model: @news, local: true) do |f| %>

            <div class="row">
                <div class="col-md-6">
                    <%= f.label :title, "Título" %>
                    <%= f.text_field :title, class: 'form-control' %>
                </div>

                <div class="col-md-6">
                    <%= f.label :noticiadate, "Data" %>
                    <%= f.date_field :noticiadate, class: 'form-control' %>
                </div>
            </div>

            <%= f.label :summary, "Sumário" %>
            <%= f.text_area :summary, class: 'form-control' %>

            <%= f.label :text, "Texto" %>
            <%= f.text_area :text, class: 'form-control' %>

            <div class="row col-md-3">
                <%= f.label :image, "Foto" %>
                <%= f.file_field :image, class: 'form-control' %>
            </div>

            <div class="row">
                <div class="col-md-3">
                    <%= f.label :spotlight, "Destaque" %>
                    <%= f.check_box :spotlight, class: 'form-control' %>
                </div>

                <div class="col-md-3">
                    <%= f.label :active, "Activo" %>
                    <%= f.check_box :active, class: 'form-control' %>
                </div>
            </div>

            <%= f.submit "Ok", class: "btn btn-primary", method: :patch %>
            <%= link_to "Cancelar", current_user, class: "btn btn-primary" %>
        <% end %>
    </div>
</div>

app/views/backoffice/_news.html.erb
<div class="row">
  <aside>
    <section>
      <h3>
        Notícias
      </h3>
    </section>
  </aside>
</div>

<div class="row">
  <aside >
    <%= form_for backoffice_news_path, method:'get' do |f| %>
        <div class="col-md-3">
          <%= text_field_tag :title, params[:title], placeholder: 'Pesquisa',class:'form-control' %>
        </div>
    <% end %>
  </aside>
</div>
<div class="row table-responsive">
  <table class="table table-striped ">
    <tr>
      <th >Nome</th>
      <th >Data</th>
      <th >Destaque</th>
      <th >Activo</th>
      <th >Ações</th>
    </tr>
    <% @news.each do |news| %>
        <tr>
          <td><%= news.title %></td>
          <td ><%= news.noticiadate %></td>
          <% if news.spotlight %>
            <td >Sim</td>
          <% else %>
            <td>Não</td>
          <% end %>
          <% if news.active %>
            <td >Sim</td>
          <% else %>
            <td>Não</td>
          <% end %>
          <td ><%= link_to "Detalhe", backoffice_show_news_path(news), class: 'btn btn-info' %>
            <%= link_to "Editar", backoffice_edit_news_path(news) , class: 'btn btn-warning' %>
            <% if admin_user?(current_user) %>
                <%= link_to "Apagar", news, method: :delete,
                            data: { confirm: "Tem a certeza que pretende eliminar esta notícia?" }, class: 'btn btn-danger' %>
            <% end %>
          </td>
        </tr>
    <% end %>

  </table>
</div>
<div class="row">
  <aside>
    <section>
      <%= link_to "Inserir", new_news_path, class: 'btn btn-default' %>
    </section>
  </aside>
</div>
<div class="row">
  <%= will_paginate @news %>
</div>

app/views/backoffice/_users.html.erb
<div class="row">
  <aside >
    <section>
      <h3>Utilizadores</h3>
    </section>
  </aside>
</div>

<div class="row">
    <%= form_for backoffice_users_path,  method: 'get' do |f| %>
        <div class="col-md-3">
          <%= text_field_tag :search, params[:search], placeholder: 'Pesquisa',class:'form-control' %>
        </div>
        <div class="col-md-3">
          <%= select_tag(:type, options_for_select([['Backoffice','Backoffice'],['Candidato','Candidato'],['Entidade','Entidade']], params[:type]),{ include_blank: 'Tipo...', :onChange => "javascript: this.form.submit();",class:'form-control'})  %>
        </div>
    <% end %>
</div>
<div id="users" class="row table-responsive">
    <table class="table table-striped">
      <tr>
        <th >Nome</th>
        <th>Tipo</th>
        <th >Ações</th>
      </tr>
      <% @users.each do |user| %>
          <tr>
            <td class="col-md-3"><%= user.name %></td>
            <td class="col-md-3"><%= user.type %></td>
            <td class="col-md-3"><%= link_to "Detalhe", backoffice_show_users_path(user), class: 'btn btn-info' %>
              <%= link_to "Editar", backoffice_edit_users_path(user), class: 'btn btn-warning' %>
              <% if admin_user?(current_user) %>
                  <%= link_to "Apagar", user, method: :delete,
                              data: { confirm: "Tem a certeza que pretende eliminar este utilizador?" }, class: 'btn btn-danger' %>
              <% end %>
            </td>
          </tr>
      <% end %>
    </table>
</div>

<div class="row">
  <aside >
    <section>
      <%= link_to "Inserir", new_backoffice_path, class: 'btn btn-default' %>
    </section>
  </aside>
</div>

<div class="row">
  <aside>
    <section>
      <%= will_paginate @users %>
    </section>
  </aside>

</div>

app/views/backoffice/edit_news.html.erb
<% provide(:title, 'Inserir/Editar') %>
<% provide(:data, params[:data]) %>
<div class="row">
  <aside class="col-md-4">
    <h3>Inserir/Editar</h3>
  </aside>
</div>
<div class="row">
  <div class="col-md-12 ">
    <%= render 'edit' %>
  </div>
</div>

app/views/backoffice/edit_user_password.html.erb
<% provide(:title, 'Inserir/Editar') %>
<% provide(:data, params[:data]) %>
<div class="row">
  <aside class="col-md-4">
    <h3>Inserir/Editar</h3>
  </aside>
</div>
<div class="row">
  <div class="col-md-12 ">
    <%= simple_form_for @user, url: backoffice_edit_user_password_path do |f| %>
    <div class="row">
      <div class="col-md-6 ">
        <%= f.label :name, "Nome" %>
        <p> <%= @user.name %></p>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6 ">
        <%= f.input :password, label: "Password", hint:"Minímo de 6 carácteres" %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6 ">
        <%= f.input :password_confirmation, label: "Confirmação da Password" %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-2">
        <%= f.button :submit, class: "btn btn-primary" %>
      </div>
      <div class="col-md-2">
        <%= link_to "Cancelar", backoffice_users_path, class: "btn btn-default" %>
      </div>
    </div>
<% end %>
  </div>
</div>

app/views/backoffice/edit_users.html.erb
<% provide(:title, 'Inserir/Editar') %>
<% provide(:data, params[:data]) %>
<% provide(:backoffice, true) %>

<div class="row">
  <aside class="col-md-4">
    <h3>Inserir/Editar</h3>
  </aside>
</div>
<div class="row">
  <div class="col-md-12 ">
    <%= simple_form_for @user, url: backoffice_edit_users_path do |f| %>
        <div>
      <div id="new_info">
        <div class="row">
          <div class="col-md-6 ">
            <%= f.input :name,label: "Nome" %>
          </div>
          <div class="col-md-6">
            <%= f.label :entitie, "Tipo" %>
            <% if @user.type=="Entidade" %>
                <%= f.hidden_field :entitie, value: @user.type %>
            <% else %>
                <%= f.hidden_field :entitie, value: 0 %>
            <% end %>
            <p><%= @user.type %></p>
          </div>
        </div>
        <div class="row">
          <div class="col-md-6">
            <%= f.input :email, label: "Email" ,placeholder: 'Example: example@example.com' %>
          </div>
          <% if @user.password_digest.nil? %>
              <%= f.hidden_field :password, value: '123456 ' %>
              <%= f.hidden_field :password_confirmation, value: '123456 ' %>
          <% end %>
          <%= f.hidden_field :backoffice, value: true %>
        </div>
        <div class="row">
          <div class="col-md-2">
            <%= f.button :submit, class: "btn btn-primary" %>
          </div>
          <div class="col-md-2">
            <%= link_to "Cancelar", backoffice_users_path, class: "btn btn-default" %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  </div>
</div>

app/views/backoffice/index_news.html.erb
<%= render  'news' %>

app/views/backoffice/index_users.html.erb
<%= render 'users' %>

app/views/backoffice/new.html.erb
<div class="row">
  <aside class="col-md-4">
    <h3>Inserir/Editar</h3>
  </aside>
</div>
<%= simple_form_for @user, url: new_backoffice_path do |f| %>
    <div>
      <div id="new_info">
        <div class="row">
          <div class="col-md-6 ">
            <%= f.input :name,label: "Nome" %>
          </div>
          <div class="col-md-6">
            <%= f.label :admin, "Tipo" %>
            
            <p>Backoffice</p>
          </div>
        </div>
        <div class="row">
          <div class="col-md-6">
            <%= f.input :email, label: "Email" ,placeholder: 'Example: example@example.com' %>
          </div>
          <% if @user.password_digest.nil? %>
              <%= f.hidden_field :password, value: '123456 ' %>
              <%= f.hidden_field :password_confirmation, value: '123456 ' %>
          <% end %>
          <%= f.hidden_field :backoffice, value: true %>
          
        </div>
        <div class="row">
          <div class="col-md-2">
            <%= f.button :submit, class: "btn btn-primary" %>
          </div>
          <div class="col-md-2">
            <%= link_to "Cancelar", backoffice_users_path, class: "btn btn-default" %>
          </div>
        </div>
      </div>
    </div>
<% end %>

app/views/backoffice/show_news.html.erb
<div class="row">
  <aside class="col-md-4">
    <section>
      <h3>Detalhe da Notícia</h3>
    </section>
  </aside>
</div>
<div class="row">
  <aside class="col-md-6">
    <section>
      <p><strong>Título</strong></p>
      <p><%= @news.title %></p>
    </section>
  </aside>
  <aside class="col-md-6">
    <section>
      <p><strong>Data</strong></p>
      <p><%= @news.noticiadate %></p>
    </section>
  </aside>
</div>

<div class="row">
  <aside class="col-md-12">
    <section>
      <p><strong>Sumário</strong></p>
      <p><%= raw @news.summary %></p>
      <p><strong>Texto</strong></p>
      <p><%= raw @news.text %></p>
    </section>
  </aside>
</div>
<div class="row">
  <aside class="col-md-6">
    <section>
      <p><strong>Imagem</strong></p>
      <%= image_tag @news.display_image if @news.image.attached? %>
    </section>
  </aside>
</div>
<div class="row">
  <aside class="col-md-6">
    <section>
      <p><strong>Destaque</strong></p>
      <% if @news.spotlight %>
        <p>Sim</p>
      <% else %>
        <p>Não</p>
      <% end %>
    </section>
  </aside>
  <aside class="col-md-6">
    <section>
      <p><strong>Activa</strong></p>
      <% if @news.active %>
        <p>Sim</p>
      <% else %>
        <p>Não</p>
      <% end %>
    </section>
  </aside>
</div>
<div class="row">
  <%= link_to "Editar", backoffice_edit_news_path(@news),class: 'btn btn-default' %>
  <% if current_user.admin? %>
      <%= link_to "Apagar", @news, method: :delete,
                  data: { confirm: "Tem a certeza que pretende eliminar esta notícia?" }, class: 'btn btn-danger' %>
  <% end %>
  <%= link_to "Inserir", new_news_path,class: 'btn btn-default' %>
  <%= link_to "Listagem", backoffice_news_path ,class: 'btn btn-default' %>
</div>

app/views/backoffice/show_users.html.erb
<div class="row">
  <aside class="col-md-4">
    <section>
      <h3>Detalhe do Utilizador</h3>
    </section>
  </aside>
</div>
<div class="row">
  <aside class="col-md-6">
    <section>
      <p><strong>Nome</strong></p>
      <p><%= @user.name %></p>
    </section>
  </aside>
  <aside class="col-md-6">
    <section>
      <p><strong>Tipo</strong></p>
      <p><%= @user.type %></p>
    </section>
  </aside>
</div>

<div class="row">
  <aside class="col-md-6">
    <section>
      <p><strong>Email</strong></p>
      <p><%= @user.email %></p>
    </section>
  </aside>
</div>
<div class="row">
  <%= link_to "Editar", backoffice_edit_users_path(@user),class: 'btn btn-default' %>
  <%= link_to "Alterar Password", backoffice_edit_user_password_path(@user),class: 'btn btn-default' %>
  <% if current_user.admin? %>
      <%= link_to "Apagar", @user, method: :delete,
                  data: { confirm: "Tem a certeza que pretende eliminar este utilizador?" }, class: 'btn btn-danger' %>
  <% end %>
  <%= link_to "Inserir", new_backoffice_url,class: 'btn btn-default' %>
  <%= link_to "Listagem", backoffice_users_path ,class: 'btn btn-default' %>
</div>