config/routes.rb
Rails.application.routes.draw do
  root 'global_pages#home'
  get '/home', to: 'global_pages#home'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/edit/password', to: 'password#edit'

  get '/signup', to: 'global_pages#signup'
  get '/signupcandidato', to:'candidatos#new'
  get '/signupentidade', to:'entidades#new'
  get '/new/offer', to:'offers#new'
  get 'new/news', to:'news#new'

  get '/candidatos', to:'candidatos#index'
  get '/entidades', to: 'entidades#index'
  get '/offers', to: 'offers#index'
  get '/news', to: 'news#index'
  
  resources :candidatos do
    member do
      get :offerings, :offerends
    end
  end

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :users, :entidades, :offers, :news
  resources :candidaturas, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

  #BACKOFFICE
  get '/backoffice', to: 'backoffice#home'
  get '/backoffice/users', to: 'backoffice#index_users'
  get '/backoffice/news', to: 'backoffice#index_news'
  get '/backoffice/users/:id', to: 'backoffice#show_users', as: 'backoffice_show_users'
  get '/backoffice/news/:id', to: 'backoffice#show_news', as: 'backoffice_show_news'
  get '/backoffice/news/:id/edit', to:'backoffice#edit_news', as: 'backoffice_edit_news'
  patch '/backoffice/news/:id/edit', to:'news#update'
  get '/backoffice/users/:id/edit', to:'backoffice#edit_users', as: 'backoffice_edit_users'
  get '/backoffice/users/:id/edit_password', to:'backoffice#edit_user_password', as: 'backoffice_edit_user_password'
  patch '/backoffice/users/:id/edit_password', to:'users#update'
  patch '/backoffice/users/:id/edit', to:'users#update'
  post '/backoffice/new', to:'users#create'
  resources :backoffice
  
end

app/controllers/global_pages_controller.rb
class GlobalPagesController < ApplicationController
  def home
    @ent = Entidade.all.order(created_at: :desc)
    @can = Candidato.all.order(created_at: :desc)
    @entidades = @ent.limit(3)
    @candidatos = @can.limit(3)
    @news = News.all.limit(3).order(updated_at: :desc)
    @offers = Offer.all.limit(3).order(created_at: :desc)
  end
end

app/helpers/global_pages_helper.rb
module GlobalPagesHelper
end

app/views/global_pages/home.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <h2>Últimas Ofertas</h2>
            <%= render @offers %>
            <%= link_to "Ver todas as ofertas", offers_path %>
        </div>
        <div class="col-md-6">
            <h2>Notícias</h2>
            <%= render @news %>
            <%= link_to "Ver todas as notícias", news_path %>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6">
            <h2>Últimas Empresas</h2>
            <%= render @entidades %>
            <%= link_to "Ver todas as empresas", entidades_path %>
        </div>

        <div class="col-md-6">
            <h2>Últimos Candidatos</h2>
            <%= render @candidatos %>
            <%= link_to "Ver todos os candidatos", candidatos_path %>
        </div>
    </div>
</div>

app/views/global_pages/signup.html.erb
<div class="center jumbotron">
    <h2>Novo Registo</h1>
<br/>
    <div class="center row">
        <%= link_to "Sou uma entidade", signupentidade_path, class: "btn btn-lg btn-primary" %>
    </div>
<br/>
    <div class="center row">
        <%= link_to "Sou um candidato", signupcandidato_path, class: "btn btn-lg btn-primary" %>
    </div>
</div>