config/routes.rb
Rails.application.routes.draw do
  root 'global_pages#home'
  get '/home', to: 'global_pages#home'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/edit/password', to: 'password#edit'

  get '/signup', to: 'global_pages#signup'
  get '/signupcandidato', to:'candidatos#new'
  get '/signupentidade', to:'entidades#new'
  get '/new/offer', to:'offers#new'
  get 'new/news', to:'news#new'

  get '/candidatos', to:'candidatos#index'
  get '/entidades', to: 'entidades#index'
  get '/offers', to: 'offers#index'
  get '/news', to: 'news#index'
  
  resources :candidatos do
    member do
      get :offerings, :offerends
    end
  end

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :users, :entidades, :offers, :news
  resources :candidaturas, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

  #BACKOFFICE
  get '/backoffice', to: 'backoffice#home'
  get '/backoffice/users', to: 'backoffice#index_users'
  get '/backoffice/news', to: 'backoffice#index_news'
  get '/backoffice/users/:id', to: 'backoffice#show_users', as: 'backoffice_show_users'
  get '/backoffice/news/:id', to: 'backoffice#show_news', as: 'backoffice_show_news'
  get '/backoffice/news/:id/edit', to:'backoffice#edit_news', as: 'backoffice_edit_news'
  patch '/backoffice/news/:id/edit', to:'news#update'
  get '/backoffice/users/:id/edit', to:'backoffice#edit_users', as: 'backoffice_edit_users'
  get '/backoffice/users/:id/edit_password', to:'backoffice#edit_user_password', as: 'backoffice_edit_user_password'
  patch '/backoffice/users/:id/edit_password', to:'users#update'
  patch '/backoffice/users/:id/edit', to:'users#update'
  post '/backoffice/new', to:'users#create'
  resources :backoffice
  
end

app/models/entidade.rb
class Entidade < User
    has_many :offers, dependent: :destroy

    scope :search, -> (search) {where("name like ? OR presentation like ?","#{search}%","%#{search}%")}
    scope :locality, -> (local) { where locality: local}
    scope :professionalactivity, -> (area) { where professionalactivity: area}

    VALIDATE_NUMBER = /\A[+-]?\d+\z/i
    validates :nif, format: { with: VALIDATE_NUMBER },
                   length: { minimum: 9, maximum: 9 }
    validates :professionalactivity, presence: true
end

app/controllers/entidades_controller.rb
class EntidadesController < ApplicationController

  def index
    @entidades = Entidade.order(created_at: :desc)
    filtering_params(params).each do |key, value|
      @entidades = @entidades.public_send(key,value) if value.present?
    end
    @entidades = @entidades.paginate(page: params[:page], per_page:8)
  end

  def show
    @entidade = Entidade.find(params[:id])
    @offers = @entidade.offers.paginate(page: params[:page])
    @followers = @entidade.followers.paginate(page:params[:page], per_page:2)
  end

  def new
    @entidade = Entidade.new
  end

  def edit
    @entidade = Entidade.find(params[:id])
  end

  def create 
    @entidade = Entidade.new(entidade_params)
    if @entidade.save
      log_in @entidade
      redirect_to @entidade
    else
      render 'new'
    end
  end

  def update
    @entidade = Entidade.find(params[:id])
    if @entidade.update(entidade_params)
      redirect_to @entidade
    elsif @entidade.update(password_params)
      redirect_to @entidade
    else
      render 'edit'
    end
  end

  private 

    def entidade_params
      params.require(:entidade).permit(
        :email,
        :name,
        :password,
        :password_confirmation,
        #:photo,
        :address,
        :postal_code,
        :locality,
        :contacts,
        :page,
        :presentation,
        :nif,
        :professionalactivity
      )
    end

    def password_params
      params.require(:entidade).permit(
        :password,
        :password_confirmation
      )
    end

    #filters parameters from params
    def filtering_params(params)
      params.slice(:search,:professionalactivity,:locality)
    end
end

app/helpers/entidades_helper.rb
module EntidadesHelper

    # Returns the Gravatar for the given entidade.
    def gravatar_for(entidade, size: 80)
        gravatar_id = Digest::MD5::hexdigest(entidade.email.downcase)
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
        image_tag(gravatar_url, alt: entidade.name, class: "gravatar")
    end
end

app/views/entidades/_entidade.html.erb
<li>
    <%= gravatar_for entidade, size: 80 %>
    <% @entidade = entidade %>
    <ul>
        <li><%= link_to @entidade.name, @entidade %></li>
    
        <li><%= raw @entidade.presentation %></li>
    </ul>
    <% if !current_user.nil? %>
        <% if current_user.type %>
            <% if current_user.type.downcase=="candidato" %>
                <% if current_user.following?(@entidade) %>
                    <%= render 'entidades/unfollow' %>
                <% else %>
                    <%= render 'entidades/follow' %>
                <% end %>
            <% end %>
        <% elsif current_user.id==@entidade.id || current_user.admin %>
            <%= link_to "Editar", edit_entidade_path(@entidade), class: "btn btn-default" %>
        <% end %>
    <% end %>
</li>

app/views/entidades/_follow.html.erb
<%= form_for(current_user.active_relationships.build, remote: true) do |f| %>
    <div><%= hidden_field_tag :followed_id, @entidade.id %></div>
    <%= f.submit "Interessado/a", class: "btn btn-default" %>
<% end %>

app/views/entidades/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @entidade.id),
             html: { method: :delete }, remote: true) do |f| %>
    <%= f.submit "Retirar Interesse", class: "btn btn-default" %>
<% end %>

app/views/entidades/edit.html.erb
<% provide(:title, 'Editar Entidade') %>
<h3>Editar Entidade</h3>

<div class="row">
    <div class="col-md-12">
        <%= form_with(model: @entidade, local: true) do |f| %>

            <div class="row">
                <div class="col-md-5">
                    <%= f.label :email %>
                    <%= f.email_field :email, class: 'form-control' %>
                </div>
            </div>

            <div class="row">
                <div class="col-md-5">
                    <%= f.label :name, "Nome" %>
                    <%= f.text_field :name, class: 'form-control' %>
                </div>
                
                <div class="col-md-3 col-md-offset-2">
                    <%= f.label :photo, "Foto" %>
                    <%= f.file_field :photo, class: 'form-control' %>
                </div>
            </div>

            <div class="row col-md-12">
                <%= f.label :address, "Morada" %>
                <%= f.text_area :address, class: 'form-control' %>
            </div>

            <div class="row">
                <div class="col-md-2">
                    <%= f.label :postal_code, "Código Postal" %>
                    <%= f.text_field :postal_code, class: 'form-control' %>
                </div>
                
                <div class="col-md-2 col-md-offset-5">
                    <%= f.label :locality, "Localidade" %>
                    <%= f.text_field :locality, class: 'form-control' %>
                </div>
            </div>

            <%= f.label :contacts, "Contactos" %>
            <%= f.text_field :contacts, class: 'form-control' %>

            <%= f.label :page, "Página" %>
            <%= f.text_field :page, class: 'form-control' %>

            <%= f.label :nif, "NIF" %>
            <%= f.text_field :nif, class: 'form-control' %>

            <%= f.label :professionalactivity, "Atividade Profissional" %>
            <%= f.select :professionalactivity, (["Informática", "Design"]), class: 'form-control' %>

            <%= f.label :presentation, "Apresentação" %>
            <%= f.text_area :presentation, class: 'form-control' %>

            <%= f.submit "Ok", class: "btn btn-primary" %>
            <%= link_to "Cancelar", current_user, class: "btn btn-primary" %>
        <% end %>
    </div>
</div>

app/views/entidades/index.html.erb
<% provide(:title, "Entidades") %>
<h2>Entidades</h2>

<div class="row">
  <aside>
    <%= form_for entidades_path, method: 'get' do %>
        <div class="col-md-3">
          <%= text_field_tag :search, params[:search], placeholder: 'Pesquisa', class: 'form-control' %>
        </div>
        <div class="col-md-3">
          <% field_array = Entidade.all.distinct.pluck(:professionalactivity) %>
          <%= select_tag(:professionalactivity , options_for_select(field_array,params[:professionalactivity]),{include_blank: 'Área de actividade...', :onChange => "javascript: this.form.submit();", class: 'form-control'}) %>
        </div>
        <div class="col-md-3">
          <% field_array = Entidade.all.distinct.pluck(:locality) %>
          <%= select_tag(:locality, options_for_select(field_array, params[:locality]),{include_blank: 'Concelho...', :onChange => "javascript: this.form.submit();", class: 'form-control'}) %>
        </div>
    <% end %>
  </aside>
</div>

<ul class="users">
    <%= render @entidades %>
</ul>

<%= will_paginate @entidades %>

app/views/entidades/new.html.erb
<% provide(:title, 'Nova Entidade') %>
<h3>Nova Entidade</h3>

<div class="row">
    <div class="col-md-12">
        <%= form_with(model: @entidade, local: true) do |f| %>

            <div class="row">
                <div class="col-md-5">
                    <%= f.label :email %>
                    <%= f.email_field :email, class: 'form-control' %>
                </div>
            </div>

            <div class="row">
                <div class="col-md-5">
                    <%= f.label :password %>
                    <%= f.password_field :password, class: 'form-control' %>
                </div>
                
                <div class="col-md-5 col-md-offset-2">
                    <%= f.label :password_confirmation, "Confirmação da Password" %>
                    <%= f.password_field :password_confirmation, class: 'form-control' %>
                </div>
            </div>

            <div class="row">
                <div class="col-md-5">
                    <%= f.label :name, "Nome" %>
                    <%= f.text_field :name, class: 'form-control' %>
                </div>
                
                <div class="col-md-3 col-md-offset-2">
                    <%= f.label :photo, "Foto" %>
                    <%= f.file_field :photo, class: 'form-control' %>
                </div>
            </div>

            <div class="row col-md-12">
                <%= f.label :address, "Morada" %>
                <%= f.text_area :address, class: 'form-control' %>
            </div>

            <div class="row">
                <div class="col-md-2">
                    <%= f.label :postal_code, "Código Postal" %>
                    <%= f.text_field :postal_code, class: 'form-control' %>
                </div>
                
                <div class="col-md-2 col-md-offset-5">
                    <%= f.label :locality, "Localidade" %>
                    <%= f.text_field :locality, class: 'form-control' %>
                </div>
            </div>

            <%= f.label :contacts, "Contactos" %>
            <%= f.text_field :contacts, class: 'form-control' %>

            <%= f.label :page, "Página" %>
            <%= f.text_field :page, class: 'form-control' %>

            <%= f.label :presentation, "Apresentação" %>
            <%= f.text_area :presentation, class: 'form-control' %>

            <%= f.label :nif, "NIF" %>
            <%= f.text_field :nif, class: 'form-control' %>

            <%= f.label :professionalactivity, "Atividade Profissional" %>
            <%= f.select :professionalactivity, (["Informática", "Design", "Engenharia Civil"]), class: 'form-control' %>

            <%= f.submit "Registar", class: "btn btn-primary" %>
        <% end %>
    </div>
</div>

app/views/entidades/show.html.erb
<% provide(:title, @entidade.name) %>

<% if current_user?(@entidade) %>

    <div class="row">
        <div class="col-md-7">
            <h3>Ofertas</h3>
            <% if @entidade.offers.any? %>
                <ol>
                    <%= render @offers %>
                </ol>
                <%= will_paginate @offers %>
            <% end %>
            <%= link_to "Inserir Oferta", new_offer_path, class: "btn btn-default" %>
        </div>
        <div class="col-md-5">
            <h3>Entidade<h3>
            <%= link_to "Editar Dados", edit_entidade_path, class: "btn btn-lg btn-primary" %>
            <%= link_to "Alterar Password", edit_password_path, class: "btn btn-lg btn-primary" %>
        </div>
    </div>
    <div class="row">
        <div class="col-md-7">
            <h3>Histórico</h3>
        </div>
        <div class="col-md-5">
            <h3>Candidatos interessados</h3>
            <% if @followers.any? %>
                <%= render @followers %>
            <% else %>
                <p>Ainda não tem candidatos interessados na sua empresa.</p>
            <% end %>
        </div>
    </div>


<% else %>
    <div class="row">
        <aside class="col-md-2">
            <section class="user_info">
                <h1><%= @entidade.name %></h1>
            </section>
        </aside>
    </div>

    <div class="row">
        <div class="col-md-2">
            <%= gravatar_for @entidade, size: 160 %>
            <section>
                <% if current_user.type %>
                    <% if logged_in? && !current_user?(@entidade) && current_user.type.downcase == 'candidato' %>
                        <% if current_user.following?(@entidade)  %>
                            <%= render 'entidades/unfollow' %>
                        <% else %>
                            <%= render 'entidades/follow' %>
                        <% end %>
                    <% end %>
                <% end %>
                <% if current_user %>
                    <% if current_user?(@entidade) || current_user.admin %>
                        <%= link_to "Editar", edit_user_path(@entidade), class: 'btn btn-default' %>
                    <% end %>
                <% end %>
            </section>
        </div>

        <div class="col-md-8 col-md-offset-2">

            <%= raw @entidade.presentation %> 

            <h4>Atividade Profissional</h4>
            <%= @entidade.professionalactivity %> 

            <h4>Morada</h4>
            <%= raw @entidade.address %> 
            <%= @entidade.postal_code %>  <%= @entidade.locality %> 

            <h4>Contactos</h4>
            <%= @entidade.contacts %> 
            <br/>
            <a href="#{@entidade.page}"><%= @entidade.page %></a>

        </div>
    </div>

    <div class="row">
        <% if @entidade.offers.any? %>
            <h3>Ofertas Activas (<%= @entidade.offers.count %>)</h3>
            <ol class="ofertas">
                <%= render @offers %>
            </ol>
            <%= will_paginate @offers %>
        <% end %>
    </div>
   
    <%= link_to "Ver entidades", entidades_path %>
<% end %>