config/routes.rb
Rails.application.routes.draw do
  root 'global_pages#home'
  get '/home', to: 'global_pages#home'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/edit/password', to: 'password#edit'

  get '/signup', to: 'global_pages#signup'
  get '/signupcandidato', to:'candidatos#new'
  get '/signupentidade', to:'entidades#new'
  get '/new/offer', to:'offers#new'
  get 'new/news', to:'news#new'

  get '/candidatos', to:'candidatos#index'
  get '/entidades', to: 'entidades#index'
  get '/offers', to: 'offers#index'
  get '/news', to: 'news#index'
  
  resources :candidatos do
    member do
      get :offerings, :offerends
    end
  end

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :users, :entidades, :offers, :news
  resources :candidaturas, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

  #BACKOFFICE
  get '/backoffice', to: 'backoffice#home'
  get '/backoffice/users', to: 'backoffice#index_users'
  get '/backoffice/news', to: 'backoffice#index_news'
  get '/backoffice/users/:id', to: 'backoffice#show_users', as: 'backoffice_show_users'
  get '/backoffice/news/:id', to: 'backoffice#show_news', as: 'backoffice_show_news'
  get '/backoffice/news/:id/edit', to:'backoffice#edit_news', as: 'backoffice_edit_news'
  patch '/backoffice/news/:id/edit', to:'news#update'
  get '/backoffice/users/:id/edit', to:'backoffice#edit_users', as: 'backoffice_edit_users'
  get '/backoffice/users/:id/edit_password', to:'backoffice#edit_user_password', as: 'backoffice_edit_user_password'
  patch '/backoffice/users/:id/edit_password', to:'users#update'
  patch '/backoffice/users/:id/edit', to:'users#update'
  post '/backoffice/new', to:'users#create'
  resources :backoffice
  
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
        <%= link_to "Bolsa de Emprego", root_path, id: "logo" %>
        <nav>
            <ul class="nav navbar-nav navbar-right">
                <% if logged_in? %>
                    <% if admin_user?(current_user) %>
                        <li><%= link_to @current_user.name,  backoffice_url %></li>
                    <% else %>
                        <li><%= link_to "Perfil", current_user %></li>
                    <% end %>
                    <li class="divider"></li>
                    <li><%= link_to "Sair", logout_path, method: :delete %></li>
                <% else %>
                    <li><%= link_to "Registar-me", signup_path %></li>
                    <li class="divider"></li>
                    <li><%= link_to "Login", login_path %></li>
                <% end %>
            </ul>
            <ul class="nav navbar-nav navbar-left">
                <li><%= link_to "Home", root_path %></li>
                <% if admin_user?(current_user) %>
                    <li><%= link_to "Utilizadores",   backoffice_users_url %></li>
                    <li class="divider"></li>

                    <li><%= link_to "Notícias", backoffice_news_url  %></li>
                <% else %>
                    <li><%= link_to "Entidades", entidades_path %></li>
                    <li class="divider"></li>
                    <li><%= link_to "Candidatos", candidatos_path %></li>
                    <li class="divider"></li>
                    <li><%= link_to "Ofertas", offers_path %></li>
                    <li class="divider"></li>
                    <li><%= link_to "Notícias", news_path %></li>
                <% end %>
            </ul>
        </nav>
    </div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
    </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <script src="https://cdn.tiny.cloud/1/s2rgstzapx9pwt2lzp452bf7v3307xlgvfoxffqn3ae8vqi9/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <script>
      tinymce.init({
      selector: 'textarea',
        plugins: 'a11ychecker advcode casechange formatpainter linkchecker lists checklist media mediaembed pageembed permanentpen powerpaste table advtable tinycomments tinymcespellchecker',
        toolbar: 'a11ycheck addcomment showcomments casechange checklist code formatpainter pageembed permanentpen table',
        toolbar_drawer: 'floating',
        tinycomments_mode: 'embedded',
        tinycomments_author: 'Author name',
      });
    </script>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>